### ISSUE TITLE
Install on UNRAID

### ISSUE THREAD

**Issue by guim31** [isc30/eMulerr#1]
I don´t know how to add the dependency to radarr, as I'm using it on my Unraid server.

Maybe someone could explain it to me ?

```
radarr:
   image: lscr.io/linuxserver/radarr:latest
+  depends_on:
+    emulerr:
+      condition: service_healthy
```

**Comment by isc30** [comment]
Hey, that part is optional and only usable if radarr and emulerr live in
the same docker-compose

**Comment by guim31** [comment]
Thanks for your answer.

Unfortunatly I was unable to run your app on my Unraid server (quite a noob, I don't have the skills to edit the config / compiose file to make it work).

**Comment by guim31** [comment]
Thanks for your help.
Unraid uses usually a template for the docker containers to be launched.

However I can use docker-compose too.
But when I copy the compose text like this (port 3000 is already in use on my machine) : 

```
emulerr:
  image: isc30/emulerr:latest
  container_name: emulerr
  restart: unless-stopped
  tty: true
  environment:
    - PUID=99
    - PGID=100
    - PORT=3000 # optional, default=3000
    - ED2K_PORT=4662 # optional, default=4662
    - LOG_LEVEL=info # optional, default=info
  ports:
    - "3000:3000" # web ui
    - "4662:4662" # ed2k tcp
    - "4662:4662/udp" # ed2k udp
    - "4665:4665/udp" # optional, ed2k global search udp (tcp port +3)
  volumes:
    - /mnt/user/appdata/emulerr:/config # required
    - /mnt/user/downloads/nzb_torrents_completed/:/downloads # required
 ```

It gives me this error message : 
`validating /boot/config/plugins/compose.manager/projects/emulerr/docker-compose.yml: (root) Additional property emulerr is not allowed`

**Comment by isc30** [comment]
Hi, I have updated the README to better reflect the `docker-compose` configuration.
In your case it would be:

```yml
services:
  emulerr:
    image: isc30/emulerr:latest
    container_name: emulerr
    restart: unless-stopped
    tty: true
    environment:
      - PUID=99
      - PGID=100
    ports:
      - "3000:3000" # web ui
      - "4662:4662" # ed2k tcp
      - "4662:4662/udp" # ed2k udp
      - "4665:4665/udp" # ed2k global search udp (tcp port +3)
    volumes:
      - /mnt/user/appdata/emulerr:/config
      - /mnt/user/downloads/nzb_torrents_completed:/downloads
```
