### ISSUE TITLE
Problems Running Emulerr in Docker on Synology NAS with DSM 7 Container Manager

### ISSUE THREAD

**Issue by Mika3578** [isc30/eMulerr#10]
### Description
I encountered issues while trying to install Emulerr in Docker using the Container Manager assistant on a Synology NAS running DSM 7. The container did not start properly and kept restarting in a loop, unable to find the directory `/downloads/complete`.

### Steps to Reproduce
1. Follow the instructions for setting up Emulerr in Docker.
2. Use the following `docker-compose.yml` file as reference:

    ```yaml
    version: '3.8'

    services:
      emulerr:
        image: isc30/emulerr
        container_name: emulerr
        volumes:
          - ./config:/config # required
          - ./downloads:/downloads # required -> ./downloads:/downloads/complete
          - ./shared:/shared:ro # optional, extra files to be shared via ed2k/kad
        ports:
          - 8080:8080
        restart: always
    ```

### Expected Behavior
The container should start properly and Emulerr should be accessible via the specified port.

### Actual Behavior
The container restarts continuously and logs an error indicating that it cannot find the directory `/downloads/complete`.

### Additional Information
There may be an error in the `docker-compose.yml` file regarding the volume mapping for the downloads folder. The following change might resolve the issue:

```yaml
- ./downloads:/downloads # required
+ ./downloads:/downloads/complete # corrected
