### ISSUE TITLE
Best way to modify amule.conf?

### ISSUE THREAD

**Issue by Jorman** [isc30/eMulerr#9]
Hi,

I would need to edit `amule.conf`, could you please point me to the best method to do that, taking into account your design?
Let me explain, I come from `amule`, the `ngosang` version, where I modified the `amule.conf` file to enable for example UPNP and other things.
I tried editing the one generated by `eMulerr` but I realized that it gets overwritten on every reboot.
Looking closer, I saw that you do it directly with the `entrypoint.sh` file.

Do you think it is "easier" and faster if I clone your `entrypoint.sh`, make the changes I want on the `amule.conf` file and use the new `entrypoint.sh` or is there a better method you recommend?

**Comment by jrhigueras** [comment]
My temporary solution to this is to add an entrypoint parameter to the docker compose setting your own script:
```yaml
services:
  emulerr:
    image: isc30/emulerr:latest
    container_name: emulerr
    restart: unless-stopped
    tty: true
    entrypoint: /scripts/entrypoint.sh
    environment:
      - PUID=1000
      - PGID=1000
      - PORT=3000 # optional, default=3000
      - ED2K_PORT=4662 # optional, default=4662
      - LOG_LEVEL=info # optional, default=info
      - PASSWORD=1234 # optional, user=emulerr
    ports:
      - "3000:3000" # web ui
      - "4662:4662" # ed2k tcp
      - "4662:4662/udp" # ed2k udp
      - "4665:4665/udp" # optional, ed2k global search udp (tcp port +3)
    volumes:
      - ./config:/config # required
      - ./downloads:/downloads # required
      - ./shared:/shared:ro # optional, extra files to be shared via ed2k/kad
      - ./scripts:/scripts:ro
```
But make sure that the entrypoint you define, is accessible from the container, as it is run from inside. In my case, I achieve this by passing the "scripts" folder as volume.

By the way, the entrypoint script I'm using is exactly the same that is in the repository, but commenting the line that replaces the `amule.conf` file:
```bash
cp /config-base/amule/amule.conf /config/amule/amule.conf
```

Perhaps a better approach should be done, but for now it works for me.
